django/belt_reviewer/apps/first_app/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index,name="index"),
    url(r'^process/$', views.process,name="process"),
    url(r'^login/$', views.login,name="login"),
    url(r'^books/$', views.books,name="books"),
    url(r'^create/$', views.create,name="create"),
    url(r'^create_book/$', views.create_book,name="create_book"),
    url(r'^show/$', views.show,name="show"),
    
    # url(r'^create_review/$', views.create_review,name="create_review"),
    url(r'^logout/$', views.logout,name="logout"),
   

   
]

django/belt_reviewer/belt_reviewer/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.first_app.urls', namespace="users")),
]

django/belt_reviewer/apps/first_app/models.py
from django.db import models
import re 
import bcrypt
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

# Create your models here.
class UserManager(models.Manager):
    def validate(self, form_data):
        errors = []
        if len(form_data['first_name'])<2:
            errors.append("first name should be more than 2 characters")
        if len(form_data['last_name'])<2:
            errors.append("Last name should be more than 2 characters")
        if len(form_data['password'])<8:
            errors.append("Password should be more than 8 characters")
        if len(form_data['password'])!= len(form_data['confirm_password']):
            errors.append("Passwords donot match")

        if not EMAIL_REGEX.match(form_data['email']):
            errors.append("Email must be valid")
        user_list = User.objects.filter(email=form_data['email'])
        if user_list:
            errors.append("Email already exits")
        return errors
    def create_user(self, form_data):
        hashed_pw=bcrypt.hashpw(form_data['password'].encode(),bcrypt.gensalt())
        print(hashed_pw)
        hashed_confirm=bcrypt.hashpw(form_data['confirm_password'].encode(),bcrypt.gensalt())
        
        user= User.objects.create(
            first_name=form_data['first_name'],
            last_name=form_data['last_name'],
            email=form_data['email'],
            password=hashed_pw,
            confirm_password=hashed_confirm
                 
        )
        print(user.id)
        return user.id
    def login(self, form_data):
        errors=[]
        existing_user = User.objects.filter(email=form_data['email'])
        if not existing_user:
            return (False,"Email or password invalid")
        user = existing_user[0]
        if bcrypt.checkpw(form_data['password'].encode(), user.password.encode()):
            return(True ,user.id)


class BookManager(models.Manager):
    def create_book(self,form_data):
        print("working")
        author_name = form_data['author_first']
        if author_name =="":
            author_name = form_data['author_next']
        print(author_name)
        book=Book.objects.create(
            book_name=form_data['book_name'],
            author =   author_name  

        )
        print("working 3")
        print(book)
        return book.id
    def create_review(self,form_data,book_id,user_id):
        book = Book.objects.get(id= book_id)
        user= User.objects.get(id=user_id)
        review = Review.objects.create(
            review=form_data['review'],
            rating = form_data['stars'],
            book = book,
            reviewed_by= user
           

        ) 
        return review
       
class User(models.Model):
    first_name = models.CharField(max_length = 255)
    last_name = models.CharField(max_length = 255)
    email = models.CharField(max_length = 255)
    password = models.CharField(max_length= 255)
    confirm_password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

    
    
class Book(models.Model):
    book_name = models.CharField(max_length = 255)
    author = models.CharField(max_length = 255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = BookManager()
class Review(models.Model):
    review = models.TextField()
    rating = models.IntegerField()
    book = models.ForeignKey(Book, related_name="book_reviews")
    reviewed_by = models.ForeignKey(User, related_name="reviews")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = BookManager()

django/belt_reviewer/apps/first_app/views.py
from django.shortcuts import render,HttpResponse, redirect
from .models import User,Book,Review
from django.contrib import messages
from django.core.urlresolvers import reverse
# Create your views here.
def index(request):
    return render(request,"belt_reviewer/index.html")
def process(request):
    print("register", request.POST)
    errors = User.objects.validate(request.POST)
    if errors:
        for error in errors:
            messages.error(request,error)
        return redirect("users:index")
    user_id = User.objects.login(request.POST)
    print("first one",user_id)
    request.session['user_id']= user_id
    request.session['first_name'] = request.POST['first_name']
    print("this one '*' *30",request.session['user_id'])
    
    return redirect("users:index")
def login(request):
    print(request.POST)
    valid, result = User.objects.login(request.POST)
    if not valid:
        messages.error(request, result)
        return redirect("users:index")
    return redirect("users:books")
def books(request):
    context={
        
        "user" :  User.objects.get(id=request.session['user_id']),
        "books": Book.objects.all(),
        
        
    }
    return render(request,"belt_reviewer/books.html", context)
def create(request):
    
    return render(request,"belt_reviewer/add.html")
def create_book(request):
    print(request.POST)
    book_id = Book.objects.create_book(request.POST)
    print(book_id)
    request.session['book_id']= book_id
    request.session['book_name']= request.POST['book_name']

    review = Review.objects.create_review(request.POST,book_id=request.session['book_id'],user_id=request.session['user_id'])
    print(review)
    return redirect("users:show")
def show(request):
    context={
        "book": Book.objects.get(id=request.session['book_id']),
        "reviews": Review.objects.get(book_id=request.session['book_id'])
        }
    
    
    

    return render(request,"belt_reviewer/show.html",context)
# def create_review(request,book_id,user_id):
#     print(request.POST)
#     print("want this one",request.session['book_id'])
    
#     print (review)
#     return redirect("users:show")
def logout(request):
    request.session.clear()
    return redirect("users:index")

django/belt_reviewer/apps/first_app/templates/belt_reviewer/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add book</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet", href="{% static 'belt_reviewer/styles/style.css' %}">
</head>
<body> 
    <div class="links">
        <a class="nav-link" href="{% url 'users:books' %}">Home</a> 
        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a> 
    </div>
    <h1>Add a new book title and a Review</h1>
    
        
    <form action="/create_book/" method="post">
            {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="exampleFormControlInput1">Book Name</label>
                <input type="text" class="form-control" name="book_name" id="exampleFormControlInput1" placeholder="Book Name">

            </div>
        </div>
        
        <div class="form-row">
               
            <div class="form-group col-md-6">
                
                <label for="exampleFormControlSelect1">Author Name</label>
                <select class="form-control" name="author_first" id="exampleFormControlSelect1">
                    <option></option>
                    <option>Rick Riordon</option>
                    <option>Holly Goldberg sloan</option>
                    <option>Chetan Bhagat</option>
                    <option>Ravi shankar</option>
                    <option>RAchel Renee Russell</option>
                </select>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
            <label for="exampleFormControlInput1">Or add a new author:</label>
            <input type="text" class="form-control" name="author_next" id="exampleFormControlInput1" >
            </div>
        </div>
        <div class="form-row">
                <div class="form-group col-md-6">
                <label for="exampleFormControlTextarea1">Review</label>
                <textarea class="form-control" name="review" id="exampleFormControlTextarea1" rows="3"></textarea>
                </div>
            </div>
           
        <div class="form-group col-md-2">
            <label for="stars">Rating</label>
            <select id="stars" name="stars" class="form-control">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Add book and Review</button>
        
    </form>
    
</body>
</html>

django/belt_reviewer/apps/first_app/templates/belt_reviewer/books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Books</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet", href="{% static 'belt_reviewer/styles/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <span class="navbar-brand mb-0 h1">Welcome,{{user.first_name}} </span>
        <a class="nav-link" href="{% url 'users:create' %}">Add Book and Review</a>
        <a class="nav-link" href="{% url 'users:logout' %}">logout</a>
    </nav>
    <div class="container1">
    <h5>Recent Book Reviews:</h5>
    {% for book in books %}
    <h1><a href="/show/" value="{{book.book_id}}">{{book.book_name}}</a></h1>
    <p>Rating</p>
    <p>{{book.book_name}} says: blah blah blah</p>
    <p>Posted on {{book.created_at}}</p>
    {% endfor %}
    </div>
    <div class="container1">
        <div class="box">
            <h5>Other Books with Reviews:</h5>
            <ul>
                {% for book in books %}
                <li>{{book.book_name}}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
</html>

django/belt_reviewer/apps/first_app/templates/belt_reviewer/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>belt reviewer</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet", href="{% static 'belt_reviewer/styles/style.css' %}">

</head>
<body>
    
    <div class="container">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <h1>Welcome!</h1>
        <div class="register">
            <h2>Register</h2>
            <form action="/process/" method = 'post'>
                {% csrf_token %}
            
                <div class="row">
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="first_name" placeholder="First name">
                        </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <input type="text" class="form-control" name="last_name" placeholder="Last name">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                            
                        <input type="email" class="form-control" name="email" id="inputEmail4" placeholder="Email">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    
                        <input type="password" class="form-control" name="password" id="inputPassword4" placeholder="Password">*password should atleast be 8 characters
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    
                        <input type="password" class="form-control" name="confirm_password" id="inputPassword4" placeholder=" confirm Password">
                    </div>
                </div>
            
                    
                <button type="submit" class="btn btn-primary">Sign up</button>
            </form>
        </div>
        <div class="login">
            <h1>Login Here</h1>
            <form action="/login/" method = 'post'>
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                            
                    <input type="email" class="form-control" name="email" id="inputEmail4" placeholder="Email">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        
                        <input type="password" class="form-control" name="password" id="inputPassword4" placeholder="Password">
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>

    </div>

    
</body>
</html>

django/belt_reviewer/apps/first_app/templates/belt_reviewer/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet", href="{% static 'belt_reviewer/styles/style.css' %}">
</head>
<body>
    <div class="links">
        <a class="nav-link" href="{% url 'users:books' %}">Home</a> 
        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a> 
    </div>
    <h1>{{book.book_name}}</h1>
    <p>{{book.author}}</p>
    <h1>Reviews</h1>
    <div class="reviews">
        {% for review in book.book_reviews.all %}
        <p>Rating:{{review.rating}}</p>
        <p>{{book.book_review.first_name}} says:{{review.review}}</p>
        <p>Posted on{{review.created_at}}</p>{% endfor %}
    </div>
    <div class="box1">
        <form action="/create_book/" method="post">
            {% csrf_token %}
            <input type="hidden" name="book_name" value={{book.book_name}}>
            <input type="hidden" name="author_first" value={{book.author}}>
            <div class="form-row">
                    <div class="form-group col-md-6">
                    <label for="exampleFormControlTextarea1">Review</label>
                    <textarea class="form-control" name="review" id="exampleFormControlTextarea1" rows="3"></textarea>
                    </div>
                </div>
               
            <div class="form-group col-md-2">
                <label for="stars">Rating</label>
                <select id="stars" name="stars" class="form-control">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Submit Review</button>
        </form>
    </div>
</body>
</html>