django/user_dashboard/apps/first_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^signin/$', views.signin, name="signin"),

    url(r'^login/$', views.login, name="login"),
    url(r'^register/$', views.register, name="register"),
    url(r'^process/$', views.process, name="process"),
    url(r'^success/$', views.success, name="success"),

   
]

django/user_dashboard/user_dashboard/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.first_app.urls', namespace= "users") ),
]

django/user_dashboard/apps/first_app/models.py
from django.db import models
import re
import bcrypt

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')


# Create your models here.
class UserManager(models.Manager):
    def validate(self, form_data):
        errors = []
        if len(form_data['first_name'])<2:
            errors.append("First name should be more than 2 characters")
        if len(form_data['last_name'])<2:
            errors.append("Last name should be more than 2 characters")
        if not EMAIL_REGEX.match(form_data['email']):
            errors.append("Email should be valid")
        if len(form_data['password']) != len(form_data['confirm_password']):
            errors.append("passwords donot match")
        user_list = self.filter(email=form_data['email'])
        if user_list:
            errors.append("Email already in use")
        return errors
    def create_user(self, form_data):
        # if not self.adminCreated:
        #     self.initAdminFlag()
        # if not self.adminCreated:
        #     user_level = 9
        #     self.adminCreated = True
        # else:
        #     user_level = 0
        hashed_pw=bcrypt.hashpw(form_data['password'].encode(),bcrypt.gensalt())
        
        user=User.objects.create(
            first_name=form_data['first_name'],
            last_name= form_data['last_name'],
            email= form_data['email'],
            password = hashed_pw,
            confirm_password = hashed_pw,
            # user_level = user_level
        )
        return user.id
    def login(self, form_data):
      
        print(form_data)
        errors = []
        existing_users = User.objects.filter (email = form_data['email'])
        if not existing_users:
            return(False, "Email and password not valid")
        user= existing_users[0]
        if bcrypt.checkpw(form_data['password'].encode(), user.password.encode()):
            return(True ,user.id)
        else:
            return (False,"Email and password do not match")   
    # def initAdminFlag(self):
    #     if self.getUserCount() >0:
    #         self.adminCreated = True
    #     else:
    #         self.adminCreated = False
    # def getUserCount(self):
    #     self.all().count()


class User(models.Model):
    
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    confirm_password=models.CharField(max_length=255)
    # user_level = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

django/user_dashboard/apps/first_app/views.py
from django.shortcuts import render, redirect
from . models import User
from django.contrib import messages

# Create your views here.
def index(request):
    return render(request,'user_dashboard/index.html')
def signin(request):
    return render(request,'user_dashboard/login.html')

def process(request):
    print("process",request.POST)
    errors = User.objects.validate(request.POST)
    if errors:
        for error in errors:
            messages.error(request,error)
        return redirect('users:register')
    user_id = User.objects.create_user(request.POST)
    print(user_id)
    
    return redirect('users:register')
def login(request):
    print(request.POST)
    valid, result = User.objects.login(request.POST)
    if not valid:
        messages.error(request,result)
        return redirect ('users:signin')
    return render(request,'user_dashboard/success.html')
def register(request):
    print("register",request.POST)
    return render(request,'user_dashboard/register.html')
def success(request):
    return render(request,'user_dashboard/success.html')

django/user_dashboard/apps/first_app/templates/user_dashboard/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>User Dashboard</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/jumbotron/">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/styles/style.css' %}">

        <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Test App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
    
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      
    </ul>
    <a class="nav-link" href="{% url 'users:signin' %}">sign in</a>
  </div>
</nav>

<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">Welcome to the Test</h1>
      <p>We,re going to build a cool application using a MVC framework!The application was build with the Village88 folks!</p>
      <p><a class="btn btn-primary btn-lg" href="{% url 'users:signin' %}" role="button">Start &raquo;</a></p>
    </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-4">
        <h2>Manage Users</h2>
        <p>Using this application, you will learn how to add, remove and edit users for the application.  </p>
        
      </div>
      <div class="col-md-4">
        <h2>Leave messages</h2>
        <p>Users will be able to leave a message to another user using this application. </p>
        
      </div>
      <div class="col-md-4">
        <h2>Edit User Information</h2>
        <p>Admins will be able to edit another users information (email address, first namne, last name etc..,)</p>
        
      </div>
    </div>

    <hr>

  </div> <!-- /container -->

</main>

<!-- <footer class="container">
  <p>&copy; Company 2017-2019</p>
</footer> -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script></body>
</html>

django/user_dashboard/apps/first_app/templates/user_dashboard/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    
    <title>Test App</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/styles/style.css' %}">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
  </head>

    <body class="text-center">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form class="form-signin" action="{% url 'users:login' %}" method = 'post'>
            {% csrf_token %}
        
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" name="email" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
        
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        
        </form>
        <!-- <form action="{% url 'users:login' %}" method = 'post'>
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                        
                <input type="email" class="form-control" name="email" id="inputEmail4" placeholder="Email">
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    
                    <input type="password" class="form-control" name="password" id="inputPassword4" placeholder="Password">
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form> -->
        <a href="{% url 'users:register' %}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Don't have an account? Register here</a>

    </body>
</html>

django/user_dashboard/apps/first_app/templates/user_dashboard/register.html
<!DOCTYPE html>
<html>
    <head>
        <title>Test App</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" href="{% static 'users/styles/style.css' %}">
    </head>
    <body>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form action="{% url 'users:process' %}" method = 'post'>
            {% csrf_token %}
        
            <div class="row">
                    <div class="col-md-6">
                        <input type="text" class="form-control" name="first_name" placeholder="First name">
                    </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <input type="text" class="form-control" name="last_name" placeholder="Last name">
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                        
                    <input type="email" class="form-control" name="email" id="inputEmail4" placeholder="Email">
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                
                    <input type="password" class="form-control" name="password" id="inputPassword4" placeholder="Password">
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                
                    <input type="password" class="form-control" name="confirm_password" id="inputPassword4" placeholder="confirm">
                </div>
            </div>
                
            <button type="submit" class="btn btn-primary">Sign up</button>

        </form>
        <a href="{% url 'users:signin' %}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Already have an account? Sign in</a>


    </body>
</html>